version: 1.0
deploy:
  force: recurring
  bootstrap:
    excludes:
      - var/bootstrap
    pre-deployment-remote-commands:
      - echo "bootstrap"
  recurring:
    excludes:
      - var/recurring
    pre-deployment-remote-commands:
      - echo "recurring"